-- init.sql

CREATE DATABASE IF NOT EXISTS interndb;
USE interndb;

CREATE TABLE IF NOT EXISTS product (
    uuid VARCHAR(36) NOT NULL PRIMARY KEY,
    product_name VARCHAR(255) NOT NULL,
    quantity INT DEFAULT 0,
    price DECIMAL(10,2) NOT NULL,
    discount BOOLEAN DEFAULT FALSE,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    last_updated_by VARCHAR(50) DEFAULT 'system'
);


CREATE USER IF NOT EXISTS 'replicator'@'%' IDENTIFIED WITH mysql_native_password BY 'password';


GRANT REPLICATION SLAVE, REPLICATION CLIENT, SELECT ON *.* TO 'replicator'@'%';

FLUSH PRIVILEGES;